#pragma once

#define MCLO_EMPTY

#define MCLO_STRINGIFY_IMPL( X ) #X
#define MCLO_STRINGIFY( X ) MCLO_STRINGIFY_IMPL( X )

#define MCLO_CONCAT_IMPL( A, ... ) A##__VA_ARGS__
#define MCLO_CONCAT( A, ... ) MCLO_CONCAT_IMPL( A, __VA_ARGS__ )

#define MCLO_IIF( CONDITION ) MCLO_CONCAT_IMPL( MCLO_IIF_, CONDITION )
#define MCLO_IIF_0( TRUE_VALUE, FALSE_VALUE ) FALSE_VALUE
#define MCLO_IIF_1( TRUE_VALUE, FALSE_VALUE ) TRUE_VALUE

#define MCLO_ARG_PLACEHOLDER_1 0,
#define MCLO_TAKE_SECOND_ARG( IGNORE, VALUE, ... ) VALUE

#define MCLO_IS_DEFINED( X ) MCLO_IS_DEFINED_IMPL( X )
#define MCLO_IS_DEFINED_IMPL( X ) MCLO_IS_DEFINED_IMPL_IMPL( MCLO_ARG_PLACEHOLDER_##X )
#define MCLO_IS_DEFINED_IMPL_IMPL( ARG1_OR_JUNK ) MCLO_TAKE_SECOND_ARG( ARG1_OR_JUNK 1, 0 )

#define MCLO_DEPRECATED_ALWAYS( MSG ) [[deprecated( MSG )]]

#define MCLO_DEPRECATED( CATEGORY, MSG )                                                                               \
	MCLO_IIF( MCLO_IS_DEFINED( CATEGORY ) )( MCLO_DEPRECATED_ALWAYS( MSG ), MCLO_EMPTY )
