#pragma once

#include "mclo/meta/type_id.hpp"

#include <unordered_set>

namespace mclo
{
	/// @brief A set of type identities, keyed by type rather than by a runtime value.
	/// @details Wraps a standard set-like @p Container of @ref mclo::meta::type_id_t, exposing membership operations as
	/// templates parameterised on the type itself (e.g. @c insert<T>(), @c contains<T>()) so the @ref
	/// mclo::meta::type_id lookup is generated by the compiler. Useful for tracking which types are present, such as a
	/// set of component or event types.
	/// @note If the domain of types is fixed and known up front, prefer assigning each type an enumerator and using an
	/// @ref mclo::enum_set, which is far more efficient than a set of runtime type identities.
	/// @tparam Container The underlying set container; its key type must be @ref mclo::meta::type_id_t.
	template <typename Container = std::unordered_set<meta::type_id_t>>
	class type_id_set
	{
	public:
		using key_type = typename Container::key_type;
		using value_type = typename Container::value_type;
		using reference = typename Container::reference;
		using const_reference = typename Container::const_reference;
		using size_type = typename Container::size_type;
		using difference_type = typename Container::difference_type;
		using iterator = typename Container::iterator;
		using const_iterator = typename Container::const_iterator;

		static_assert( std::is_same_v<key_type, meta::type_id_t>,
					   "type_id_set's key type must be mclo::meta::type_id_t" );

		/// @brief Inserts the identity of type @p T into the set.
		/// @tparam T The type whose identity to insert.
		/// @return @c true if @p T was inserted, @c false if it was already present.
		template <typename T>
		bool insert()
		{
			return m_set.insert( meta::type_id<T> ).second;
		}

		/// @brief Removes the identity of type @p T from the set.
		/// @tparam T The type whose identity to erase.
		/// @return @c true if @p T was present and removed, @c false otherwise.
		template <typename T>
		bool erase() noexcept
		{
			return m_set.erase( meta::type_id<T> ) != 0;
		}

		/// @brief Checks whether the identity of type @p T is in the set.
		/// @tparam T The type whose identity to look for.
		/// @return @c true if @p T is present.
		template <typename T>
		[[nodiscard]] bool contains() const noexcept
		{
			return m_set.contains( meta::type_id<T> );
		}

		/// @brief Checks whether the identities of all of @p Ts are in the set.
		/// @tparam Ts The types whose identities to look for.
		/// @return @c true only if every type in @p Ts is present.
		template <typename... Ts>
			requires( sizeof...( Ts ) > 1 )
		[[nodiscard]] bool contains() const noexcept
		{
			return ( contains<Ts>() && ... );
		}

		/// @brief Removes all type identities from the set.
		void clear() noexcept
		{
			m_set.clear();
		}

		/// @brief Swaps the contents of this set with @p other.
		void swap( type_id_set& other ) noexcept
		{
			m_set.swap( other.m_set );
		}

		/// @brief Swaps the contents of @p lhs and @p rhs.
		friend void swap( type_id_set& lhs, type_id_set& rhs ) noexcept
		{
			lhs.swap( rhs );
		}

		/// @brief Returns @c true if the set contains no type identities.
		[[nodiscard]] bool empty() const noexcept
		{
			return m_set.empty();
		}
		/// @brief Returns the number of type identities in the set.
		[[nodiscard]] size_type size() const noexcept
		{
			return m_set.size();
		}
		/// @brief Returns the maximum number of type identities the set can hold.
		[[nodiscard]] size_type max_size() const noexcept
		{
			return m_set.max_size();
		}

		/// @brief Returns an iterator to the first type identity.
		[[nodiscard]] iterator begin() noexcept
		{
			return m_set.begin();
		}
		/// @copydoc begin()
		[[nodiscard]] const_iterator begin() const noexcept
		{
			return m_set.begin();
		}
		/// @brief Returns a const iterator to the first type identity.
		[[nodiscard]] const_iterator cbegin() const noexcept
		{
			return m_set.cbegin();
		}

		/// @brief Returns an iterator past the last type identity.
		[[nodiscard]] iterator end() noexcept
		{
			return m_set.end();
		}
		/// @copydoc end()
		[[nodiscard]] const_iterator end() const noexcept
		{
			return m_set.end();
		}
		/// @brief Returns a const iterator past the last type identity.
		[[nodiscard]] const_iterator cend() const noexcept
		{
			return m_set.cend();
		}

		/// @brief Compares two sets for ordering and equality.
		[[nodiscard]] auto operator<=>( const type_id_set& other ) const noexcept = default;

	private:
		Container m_set;
	};
}
