#pragma once

#include "mclo/strong_typedef/default_initialized.hpp"
#include "mclo/strong_typedef/semiregular.hpp"

#include "mclo/platform/attributes.hpp"

#include <concepts>
#include <type_traits>
#include <utility>

namespace mclo
{
	/// @brief Concept satisfied when Derived has opted into the behaviour of Mixin.
	/// @details True when Derived inherits the base generated by Mixin for it, including when Mixin is pulled in
	/// transitively by a bundle that composes it. Works for user defined mixins following the same tag + nested
	/// template mixin pattern, so it can be used to introspect or constrain on any composed behaviour.
	/// @tparam Derived The strong_typedef (or other CRTP host) to query.
	/// @tparam Mixin The mixin tag to check for.
	template <typename Derived, typename Mixin>
	concept has_mixin = std::derived_from<Derived, typename Mixin::template mixin<Derived>>;

	namespace detail
	{
		template <typename Mixin, typename... Mixins>
		constexpr bool contains_mixin = ( std::derived_from<Mixins, Mixin> || ... );
	}

	/// @brief A strongly typed wrapper around a value that gains behaviour from composable mixins.
	/// @details The base only stores the wrapped value and provides explicit construction from it; all other behaviour
	/// such as comparison, arithmetic, hashing or formatting is opted into via the Mixins parameter pack. Copy and move
	/// semantics are inherited from the underlying value_type by default and can be restricted with the move_only or
	/// immovable mixins. The type is swappable whenever the underlying value_type is swappable.
	///
	/// The minimal strong type wraps a value and only adds type identity, distinguished by a unique tag. The idiomatic
	/// way to spell the tag is an inline @c struct in the template argument list so it needs no separate declaration:
	/// @code
	/// using user_id = mclo::strong_typedef<std::uint64_t, struct user_id_tag>;
	/// @endcode
	///
	/// Behaviour is added by listing mixins after the tag. For most value-like types the @c semiregular and @c regular
	/// bundles are sensible defaults: @c semiregular adds default construction (value initialising the underlying), and
	/// @c regular additionally adds equality so the type behaves like a normal value:
	/// @code
	/// using name = mclo::strong_typedef<std::string, struct name_tag, mclo::regular>;
	/// using handle = mclo::strong_typedef<int, struct handle_tag, mclo::semiregular, mclo::hashable>;
	/// @endcode
	///
	/// Mixins compose freely, so a richer type can opt into several behaviours at once:
	/// @code
	/// using meters = mclo::strong_typedef<double,
	///                                     struct meters_tag,
	///                                     mclo::arithmetic,
	///                                     mclo::ordered,
	///                                     mclo::hashable,
	///                                     mclo::formattable>;
	/// @endcode
	///
	/// A custom mixin is any type with a nested @c mixin class template taking the host @c Derived type. The host
	/// inherits from @c mixin<Derived>, so the mixin can add member functions, operators or hidden friends that reach
	/// the wrapped value through @c static_cast<const Derived&>(*this).value. Following this pattern means the mixin
	/// also works with @c has_mixin for introspection:
	/// @code
	/// struct squarable
	/// {
	///     template <typename Derived>
	///     struct mixin
	///     {
	///         [[nodiscard]] constexpr auto square() const
	///         {
	///             const auto& value = static_cast<const Derived&>( *this ).value;
	///             return value * value;
	///         }
	///     };
	/// };
	///
	/// using area = mclo::strong_typedef<double, struct area_tag, squarable>;
	/// static_assert( mclo::has_mixin<area, squarable> );
	/// @endcode
	/// @tparam Wrapped The underlying value type being wrapped.
	/// @tparam Tag A phantom type distinguishing otherwise identical wrappers.
	/// @tparam Mixins The behaviour mixins to compose into the wrapper.
	template <typename Wrapped, typename Tag, typename... Mixins>
	struct MCLO_EMPTY_BASES strong_typedef : Mixins::template mixin<strong_typedef<Wrapped, Tag, Mixins...>>...
	{
		/// @brief The underlying type being wrapped.
		using value_type = Wrapped;

		/// @brief The wrapped value.
		value_type value;

		static_assert( !detail::contains_mixin<semiregular, Mixins...> || std::semiregular<value_type>,
					   "The semiregular and regular mixins require the value type to satisfy the std::semiregular "
					   "concept" );

		constexpr strong_typedef() noexcept( std::is_nothrow_default_constructible_v<value_type> )
			requires( detail::contains_mixin<default_initialized, Mixins...> &&
					  std::is_default_constructible_v<value_type> )
		= default;

		constexpr explicit strong_typedef( const value_type& raw ) noexcept(
			std::is_nothrow_copy_constructible_v<value_type> )
			: value( raw )
		{
		}

		constexpr explicit strong_typedef( value_type&& raw ) noexcept(
			std::is_nothrow_move_constructible_v<value_type> )
			: value( std::move( raw ) )
		{
		}

		friend constexpr void swap( strong_typedef& lhs,
									strong_typedef& rhs ) noexcept( std::is_nothrow_swappable_v<value_type> )
			requires( std::is_swappable_v<value_type> )
		{
			using std::swap;
			swap( lhs.value, rhs.value );
		}
	};
}
