#pragma once

#define MCLO_ARG_PLACEHOLDER_1 0,
#define MCLO_TAKE_SECOND_ARG( IGNORE, VALUE, ... ) VALUE

#define MCLO_IS_DEFINED( X ) MCLO_IS_DEFINED_IMPL( X )
#define MCLO_IS_DEFINED_IMPL( X ) MCLO_IS_DEFINED_IMPL_IMPL( MCLO_ARG_PLACEHOLDER_##X )
#define MCLO_IS_DEFINED_IMPL_IMPL( ARG1_OR_JUNK ) MCLO_TAKE_SECOND_ARG( ARG1_OR_JUNK 1, 0 )
