name: Clang Format Checker
on: [push]
jobs:
  clang-format-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: RafikFarhad/clang-format-github-action@v4
        with:
          sources: "cpp/**/*.h,cpp/**/*.pp"
          style: file